import type { InvitationStatus } from "@/lib/auth/types";
import type {
  ActivityItem,
  Invoice,
  MaintenanceTicket,
  Room,
  Tenant,
} from "@/lib/mockData";
import type {
  ChefShift,
  ChefStatus,
  DemoDorm,
  MealItemRecord,
  MealPlan,
  TenantMealPreference,
} from "@/lib/demoWorkspace";

export type WorkspaceInvitationLifecycleState = Extract<
  InvitationStatus,
  "pending" | "revoked" | "expired"
>;

export interface WorkspaceTenant extends Tenant {
  dormId: string;
  invitationLifecycleState?: WorkspaceInvitationLifecycleState;
}

export interface WorkspaceRoom extends Room {
  dormId: string;
}

export interface WorkspaceInvoice extends Invoice {
  dormId: string;
  billingPeriodKey?: string;
}

export interface WorkspaceMaintenanceTicket extends MaintenanceTicket {
  dormId: string;
  createdByTenantId?: string;
  createdByMembershipId?: string;
}

export interface WorkspaceActivityItem extends ActivityItem {
  dormId: string;
}

export interface WorkspaceChef {
  id: string;
  name: string;
  email: string;
  shift: ChefShift;
  specialty: string;
  status: ChefStatus;
  dormId: string;
  invitationLifecycleState?: WorkspaceInvitationLifecycleState;
}

function getUpcomingDayLabels(days = 7) {
  const start = new Date();
  start.setHours(0, 0, 0, 0);

  return Array.from({ length: days }, (_, index) => {
    const current = new Date(start);
    current.setDate(start.getDate() + index);
    return current.toLocaleDateString("en-US", {
      weekday: "long",
    });
  });
}

const UPCOMING_DAY_LABELS = getUpcomingDayLabels();

const DORM_MEAL_TEMPLATES = {
  "dorm-001": {
    servings: { breakfast: 22, lunch: 24, dinner: 24 },
    breakfast: [
      {
        name: "Scrambled Eggs & Toast",
        dietary: ["Vegetarian"],
        calories: 380,
      },
      { name: "Khmer Rice Porridge", dietary: ["Gluten-Free"], calories: 350 },
      { name: "Banana Pancakes", dietary: ["Vegetarian"], calories: 420 },
      { name: "Vegetable Fried Rice", dietary: ["Vegetarian"], calories: 410 },
      { name: "Chicken Congee", dietary: ["High Protein"], calories: 360 },
      { name: "Fruit Yogurt Parfait", dietary: ["Vegetarian"], calories: 320 },
      { name: "Herb Omelet Wrap", dietary: ["High Protein"], calories: 400 },
    ],
    lunch: [
      {
        name: "Grilled Chicken Rice Bowl",
        dietary: ["Gluten-Free", "High Protein"],
        calories: 620,
      },
      {
        name: "Stir-Fried Tofu Noodles",
        dietary: ["Vegetarian"],
        calories: 540,
      },
      { name: "Beef Lok Lak", dietary: ["High Protein"], calories: 690 },
      { name: "Veggie Pasta Salad", dietary: ["Vegetarian"], calories: 500 },
      {
        name: "Lemongrass Chicken Bento",
        dietary: ["High Protein"],
        calories: 610,
      },
      { name: "Mushroom Fried Rice", dietary: ["Vegetarian"], calories: 530 },
      { name: "Chicken Wraps", dietary: ["High Protein"], calories: 560 },
    ],
    dinner: [
      {
        name: "Lentil Curry & Rice",
        dietary: ["Vegan", "Gluten-Free"],
        calories: 590,
      },
      {
        name: "Baked Fish with Greens",
        dietary: ["Gluten-Free", "High Protein"],
        calories: 610,
      },
      { name: "Tofu Stir Fry", dietary: ["Vegan"], calories: 520 },
      { name: "Chicken Satay Plate", dietary: ["High Protein"], calories: 640 },
      {
        name: "Vegetable Soup & Bread",
        dietary: ["Vegetarian"],
        calories: 460,
      },
      {
        name: "Teriyaki Chicken Bowl",
        dietary: ["High Protein"],
        calories: 630,
      },
      {
        name: "Pumpkin Coconut Curry",
        dietary: ["Vegan", "Gluten-Free"],
        calories: 550,
      },
    ],
  },
  "dorm-002": {
    servings: { breakfast: 18, lunch: 20, dinner: 20 },
    breakfast: [
      {
        name: "Oatmeal with Fruits",
        dietary: ["Vegan", "Gluten-Free"],
        calories: 320,
      },
      { name: "Egg Fried Rice", dietary: ["Vegetarian"], calories: 390 },
      { name: "Peanut Butter Toast", dietary: ["Vegetarian"], calories: 340 },
      { name: "Savory Rice Porridge", dietary: ["Gluten-Free"], calories: 330 },
      { name: "Breakfast Burrito", dietary: ["High Protein"], calories: 450 },
      {
        name: "Tropical Fruit Bowl",
        dietary: ["Vegan", "Gluten-Free"],
        calories: 290,
      },
      { name: "Spinach Omelet", dietary: ["High Protein"], calories: 370 },
    ],
    lunch: [
      { name: "Veggie Pasta Salad", dietary: ["Vegetarian"], calories: 480 },
      { name: "Chicken Katsu Bowl", dietary: ["High Protein"], calories: 640 },
      { name: "Tofu Bibimbap", dietary: ["Vegetarian"], calories: 560 },
      {
        name: "Grilled Fish Rice Plate",
        dietary: ["Gluten-Free"],
        calories: 590,
      },
      {
        name: "Beef Noodle Stir Fry",
        dietary: ["High Protein"],
        calories: 620,
      },
      {
        name: "Quinoa Veggie Bowl",
        dietary: ["Vegan", "Gluten-Free"],
        calories: 500,
      },
      { name: "Chicken Caesar Wrap", dietary: ["High Protein"], calories: 560 },
    ],
    dinner: [
      {
        name: "Salmon with Steamed Veg",
        dietary: ["Gluten-Free", "High Protein"],
        calories: 650,
      },
      { name: "Vegetable Lasagna", dietary: ["Vegetarian"], calories: 610 },
      { name: "Chicken Curry", dietary: ["Gluten-Free"], calories: 630 },
      { name: "Stir-Fried Tofu & Broccoli", dietary: ["Vegan"], calories: 510 },
      {
        name: "Garlic Shrimp Rice Bowl",
        dietary: ["High Protein"],
        calories: 600,
      },
      { name: "Miso Soup & Rice Set", dietary: ["Vegetarian"], calories: 470 },
      {
        name: "Roasted Chicken Tray",
        dietary: ["High Protein"],
        calories: 620,
      },
    ],
  },
  "dorm-003": {
    servings: { breakfast: 14, lunch: 14, dinner: 14 },
    breakfast: [
      { name: "Pancakes with Syrup", dietary: ["Vegetarian"], calories: 420 },
      { name: "Veggie Omelet", dietary: ["Vegetarian"], calories: 360 },
      { name: "Banana Oat Cups", dietary: ["Vegetarian"], calories: 310 },
      { name: "Rice Noodle Soup", dietary: ["Gluten-Free"], calories: 340 },
      { name: "French Toast Sticks", dietary: ["Vegetarian"], calories: 390 },
      { name: "Yogurt and Granola", dietary: ["Vegetarian"], calories: 330 },
      { name: "Chicken Congee", dietary: ["High Protein"], calories: 350 },
    ],
    lunch: [
      { name: "Chicken Wrap", dietary: ["High Protein"], calories: 540 },
      { name: "Veggie Fried Rice", dietary: ["Vegetarian"], calories: 500 },
      { name: "Basil Beef Bowl", dietary: ["High Protein"], calories: 610 },
      {
        name: "Tofu Rice Paper Rolls",
        dietary: ["Vegan", "Gluten-Free"],
        calories: 450,
      },
      { name: "Chicken Noodle Bowl", dietary: ["High Protein"], calories: 570 },
      { name: "Vegetable Curry Bowl", dietary: ["Vegan"], calories: 520 },
      { name: "Turkey Sandwich", dietary: ["High Protein"], calories: 500 },
    ],
    dinner: [
      { name: "Soup & Bread", dietary: [], calories: 430 },
      {
        name: "Baked Chicken with Rice",
        dietary: ["High Protein"],
        calories: 610,
      },
      { name: "Veggie Stir Fry", dietary: ["Vegan"], calories: 490 },
      {
        name: "Fish Fillet with Potatoes",
        dietary: ["High Protein"],
        calories: 600,
      },
      { name: "Lentil Stew", dietary: ["Vegan", "Gluten-Free"], calories: 510 },
      { name: "Teriyaki Tofu Bowl", dietary: ["Vegetarian"], calories: 540 },
      {
        name: "Roast Chicken & Greens",
        dietary: ["High Protein"],
        calories: 620,
      },
    ],
  },
} satisfies Record<
  string,
  {
    servings: {
      breakfast: number;
      lunch: number;
      dinner: number;
    };
    breakfast: Array<{ name: string; dietary: string[]; calories: number }>;
    lunch: Array<{ name: string; dietary: string[]; calories: number }>;
    dinner: Array<{ name: string; dietary: string[]; calories: number }>;
  }
>;

function buildDemoMeals(): MealItemRecord[] {
  return Object.entries(DORM_MEAL_TEMPLATES).flatMap(([dormId, template]) =>
    UPCOMING_DAY_LABELS.flatMap((dayLabel, index) => {
      const breakfast = template.breakfast[index];
      const lunch = template.lunch[index];
      const dinner = template.dinner[index];

      return [
        {
          id: `meal-${dormId}-${index + 1}-breakfast`,
          dormId,
          name: breakfast.name,
          category: "Breakfast",
          day: dayLabel,
          servings: template.servings.breakfast + (index % 2),
          dietary: breakfast.dietary,
          status: index === 0 ? "Served" : "Planned",
          calories: breakfast.calories,
        },
        {
          id: `meal-${dormId}-${index + 1}-lunch`,
          dormId,
          name: lunch.name,
          category: "Lunch",
          day: dayLabel,
          servings: template.servings.lunch + ((index + 1) % 3),
          dietary: lunch.dietary,
          status: index === 0 ? "In Prep" : "Planned",
          calories: lunch.calories,
        },
        {
          id: `meal-${dormId}-${index + 1}-dinner`,
          dormId,
          name: dinner.name,
          category: "Dinner",
          day: dayLabel,
          servings: template.servings.dinner + (index % 3),
          dietary: dinner.dietary,
          status: "Planned",
          calories: dinner.calories,
        },
      ];
    }),
  );
}

export const DEMO_DORMS: DemoDorm[] = [
  {
    id: "dorm-001",
    name: "Sunrise Dormitory",
    city: "Phnom Penh",
    address: "12 Riverside Campus Road, Phnom Penh",
    timezone: "UTC+7 (Indochina Time)",
    waitlist: 18,
    status: "Active",
    openedOn: "2024-06-01",
  },
  {
    id: "dorm-002",
    name: "Riverside Residences",
    city: "Siem Reap",
    address: "55 Angkor Boulevard, Siem Reap",
    timezone: "UTC+7 (Indochina Time)",
    waitlist: 9,
    status: "Active",
    openedOn: "2025-01-15",
  },
  {
    id: "dorm-003",
    name: "Northgate Student House",
    city: "Battambang",
    address: "8 University Lane, Battambang",
    timezone: "UTC+7 (Indochina Time)",
    waitlist: 6,
    status: "Active",
    openedOn: "2025-08-20",
  },
];

export const DEMO_TENANTS: WorkspaceTenant[] = [
  {
    id: "tenant-001",
    dormId: "dorm-001",
    name: "Sophea Kang",
    email: "sophea.kang@dormflow.app",
    phone: "+1-555-0142",
    avatar: "SK",
    roomId: "room-001",
    moveInDate: "2025-09-01",
    status: "Active",
  },
  {
    id: "tenant-002",
    dormId: "dorm-001",
    name: "Marcus Rivera",
    email: "marcus.rivera@dormflow.app",
    phone: "+1-555-0198",
    avatar: "MR",
    roomId: "room-001",
    moveInDate: "2025-09-01",
    status: "Active",
  },
  {
    id: "tenant-003",
    dormId: "dorm-001",
    name: "Linh Tran",
    email: "linh.tran@dormflow.app",
    phone: "+1-555-0267",
    avatar: "LT",
    roomId: "room-002",
    moveInDate: "2025-10-15",
    status: "Active",
  },
  {
    id: "tenant-004",
    dormId: "dorm-001",
    name: "Ethan Park",
    email: "ethan.park@dormflow.app",
    phone: "+1-555-0334",
    avatar: "EP",
    roomId: "room-003",
    moveInDate: "2025-08-20",
    status: "Active",
  },
  {
    id: "tenant-013",
    dormId: "dorm-001",
    name: "Jade Sullivan",
    email: "jade.sullivan@dormflow.app",
    phone: "+1-555-1299",
    avatar: "JS",
    roomId: "room-004",
    moveInDate: "2026-03-27",
    status: "Inactive",
    invitationLifecycleState: "pending",
  },
  {
    id: "tenant-014",
    dormId: "dorm-001",
    name: "Noah Bennett",
    email: "noah.bennett@dormflow.app",
    phone: "+1-555-1368",
    avatar: "NB",
    roomId: "unassigned",
    moveInDate: "2025-05-20",
    status: "Inactive",
  },
  {
    id: "tenant-005",
    dormId: "dorm-002",
    name: "Amara Osei",
    email: "amara.osei@dormflow.app",
    phone: "+1-555-0411",
    avatar: "AO",
    roomId: "room-005",
    moveInDate: "2025-11-01",
    status: "Active",
  },
  {
    id: "tenant-006",
    dormId: "dorm-002",
    name: "Daniel Novak",
    email: "daniel.novak@dormflow.app",
    phone: "+1-555-0523",
    avatar: "DN",
    roomId: "room-005",
    moveInDate: "2025-09-15",
    status: "Active",
  },
  {
    id: "tenant-007",
    dormId: "dorm-002",
    name: "Priya Menon",
    email: "priya.menon@dormflow.app",
    phone: "+1-555-0618",
    avatar: "PM",
    roomId: "room-006",
    moveInDate: "2025-10-01",
    status: "Active",
  },
  {
    id: "tenant-008",
    dormId: "dorm-002",
    name: "Yuki Tanaka",
    email: "yuki.tanaka@dormflow.app",
    phone: "+1-555-0712",
    avatar: "YT",
    roomId: "room-008",
    moveInDate: "2025-07-15",
    status: "Active",
  },
  {
    id: "tenant-009",
    dormId: "dorm-002",
    name: "Nadia Flores",
    email: "nadia.flores@dormflow.app",
    phone: "+1-555-0845",
    avatar: "NF",
    roomId: "room-008",
    moveInDate: "2025-09-05",
    status: "Active",
  },
  {
    id: "tenant-010",
    dormId: "dorm-003",
    name: "Ryo Hashimoto",
    email: "ryo.hashimoto@dormflow.app",
    phone: "+1-555-0931",
    avatar: "RH",
    roomId: "room-010",
    moveInDate: "2025-08-12",
    status: "Active",
  },
  {
    id: "tenant-011",
    dormId: "dorm-003",
    name: "Kofi Asante",
    email: "kofi.asante@dormflow.app",
    phone: "+1-555-1016",
    avatar: "KA",
    roomId: "room-010",
    moveInDate: "2025-08-12",
    status: "Active",
  },
  {
    id: "tenant-012",
    dormId: "dorm-003",
    name: "Isabelle Moreau",
    email: "isabelle.moreau@dormflow.app",
    phone: "+1-555-1144",
    avatar: "IM",
    roomId: "room-012",
    moveInDate: "2025-10-09",
    status: "Active",
  },
];

export const DEMO_ROOMS: WorkspaceRoom[] = [
  {
    id: "room-001",
    dormId: "dorm-001",
    roomNumber: "101",
    type: "Double",
    floor: 1,
    capacity: 2,
    occupants: 2,
    rentPerMonth: 650,
    status: "Occupied",
    assignedTenants: ["Sophea Kang", "Marcus Rivera"],
    lastUpdated: "2026-03-20",
    amenities: ["WiFi", "AC", "Shared Bath"],
    notes: "",
  },
  {
    id: "room-002",
    dormId: "dorm-001",
    roomNumber: "102",
    type: "Single",
    floor: 1,
    capacity: 1,
    occupants: 1,
    rentPerMonth: 850,
    status: "Occupied",
    assignedTenants: ["Linh Tran"],
    lastUpdated: "2026-03-15",
    amenities: ["WiFi", "AC", "Private Bath"],
    notes: "Quiet room policy",
  },
  {
    id: "room-003",
    dormId: "dorm-001",
    roomNumber: "103",
    type: "Single",
    floor: 1,
    capacity: 1,
    occupants: 1,
    rentPerMonth: 850,
    status: "Occupied",
    assignedTenants: ["Ethan Park"],
    lastUpdated: "2026-03-10",
    amenities: ["WiFi", "AC"],
    notes: "",
  },
  {
    id: "room-004",
    dormId: "dorm-001",
    roomNumber: "104",
    type: "Double",
    floor: 1,
    capacity: 2,
    occupants: 1,
    rentPerMonth: 650,
    status: "Reserved",
    assignedTenants: ["Jade Sullivan (pending invite)"],
    lastUpdated: "2026-03-27",
    amenities: ["WiFi", "AC", "Shared Bath"],
    notes: "One bed is being held for the next onboarding wave.",
  },
  {
    id: "room-013",
    dormId: "dorm-001",
    roomNumber: "105",
    type: "Double",
    floor: 1,
    capacity: 2,
    occupants: 0,
    rentPerMonth: 670,
    status: "Available",
    assignedTenants: [],
    lastUpdated: "2026-03-28",
    amenities: ["WiFi", "AC", "Shared Bath"],
    notes: "Freshly prepared for new residents.",
  },
  {
    id: "room-005",
    dormId: "dorm-002",
    roomNumber: "201",
    type: "Triple",
    floor: 2,
    capacity: 3,
    occupants: 2,
    rentPerMonth: 540,
    status: "Occupied",
    assignedTenants: ["Amara Osei", "Daniel Novak"],
    lastUpdated: "2026-03-18",
    amenities: ["WiFi", "AC", "Shared Bath", "Balcony"],
    notes: "One bed still available",
  },
  {
    id: "room-006",
    dormId: "dorm-002",
    roomNumber: "202",
    type: "Single",
    floor: 2,
    capacity: 1,
    occupants: 1,
    rentPerMonth: 820,
    status: "Occupied",
    assignedTenants: ["Priya Menon"],
    lastUpdated: "2026-03-12",
    amenities: ["WiFi", "AC", "Private Bath"],
    notes: "Near study lounge",
  },
  {
    id: "room-007",
    dormId: "dorm-002",
    roomNumber: "203",
    type: "Double",
    floor: 2,
    capacity: 2,
    occupants: 0,
    rentPerMonth: 680,
    status: "Reserved",
    assignedTenants: [],
    lastUpdated: "2026-03-24",
    amenities: ["WiFi", "AC"],
    notes: "Reserved for April move-ins",
  },
  {
    id: "room-008",
    dormId: "dorm-002",
    roomNumber: "204",
    type: "Suite",
    floor: 2,
    capacity: 2,
    occupants: 2,
    rentPerMonth: 1200,
    status: "Occupied",
    assignedTenants: ["Yuki Tanaka", "Nadia Flores"],
    lastUpdated: "2026-03-25",
    amenities: ["WiFi", "AC", "Private Bath", "Kitchenette", "Living Area"],
    notes: "Premium suite",
  },
  {
    id: "room-009",
    dormId: "dorm-003",
    roomNumber: "301",
    type: "Double",
    floor: 3,
    capacity: 2,
    occupants: 0,
    rentPerMonth: 700,
    status: "Under Maintenance",
    assignedTenants: [],
    lastUpdated: "2026-03-23",
    amenities: ["WiFi", "AC", "Shared Bath"],
    notes: "Plumbing repair in progress",
  },
  {
    id: "room-010",
    dormId: "dorm-003",
    roomNumber: "302",
    type: "Triple",
    floor: 3,
    capacity: 3,
    occupants: 2,
    rentPerMonth: 560,
    status: "Occupied",
    assignedTenants: ["Ryo Hashimoto", "Kofi Asante"],
    lastUpdated: "2026-03-14",
    amenities: ["WiFi", "AC", "Shared Bath"],
    notes: "One bed remains open",
  },
  {
    id: "room-011",
    dormId: "dorm-003",
    roomNumber: "303",
    type: "Single",
    floor: 3,
    capacity: 1,
    occupants: 0,
    rentPerMonth: 880,
    status: "Available",
    assignedTenants: [],
    lastUpdated: "2026-03-26",
    amenities: ["WiFi", "AC", "Private Bath"],
    notes: "Ready for new tenant",
  },
  {
    id: "room-012",
    dormId: "dorm-003",
    roomNumber: "304",
    type: "Suite",
    floor: 3,
    capacity: 2,
    occupants: 1,
    rentPerMonth: 1250,
    status: "Occupied",
    assignedTenants: ["Isabelle Moreau"],
    lastUpdated: "2026-03-19",
    amenities: [
      "WiFi",
      "AC",
      "Private Bath",
      "Kitchenette",
      "Living Area",
      "Balcony",
    ],
    notes: "Second bed open for premium occupant",
  },
];

export const DEMO_INVOICES: WorkspaceInvoice[] = [
  {
    id: "inv-001",
    dormId: "dorm-001",
    tenantId: "tenant-001",
    tenantName: "Sophea Kang",
    roomNumber: "101",
    amount: 650,
    dueDate: "2026-04-01",
    issuedDate: "2026-03-15",
    status: "Issued",
    period: "April 2026",
  },
  {
    id: "inv-002",
    dormId: "dorm-001",
    tenantId: "tenant-002",
    tenantName: "Marcus Rivera",
    roomNumber: "101",
    amount: 650,
    dueDate: "2026-04-01",
    issuedDate: "2026-03-15",
    status: "Paid",
    period: "April 2026",
  },
  {
    id: "inv-003",
    dormId: "dorm-001",
    tenantId: "tenant-003",
    tenantName: "Linh Tran",
    roomNumber: "102",
    amount: 850,
    dueDate: "2026-03-01",
    issuedDate: "2026-02-15",
    status: "Overdue",
    period: "March 2026",
  },
  {
    id: "inv-004",
    dormId: "dorm-001",
    tenantId: "tenant-004",
    tenantName: "Ethan Park",
    roomNumber: "103",
    amount: 850,
    dueDate: "2026-04-01",
    issuedDate: "2026-03-15",
    status: "Paid",
    period: "April 2026",
  },
  {
    id: "inv-013",
    dormId: "dorm-001",
    tenantId: "tenant-001",
    tenantName: "Sophea Kang",
    roomNumber: "101",
    amount: 650,
    dueDate: "2026-03-01",
    issuedDate: "2026-02-15",
    status: "Paid",
    period: "March 2026",
  },
  {
    id: "inv-014",
    dormId: "dorm-001",
    tenantId: "tenant-002",
    tenantName: "Marcus Rivera",
    roomNumber: "101",
    amount: 650,
    dueDate: "2026-02-01",
    issuedDate: "2026-01-15",
    status: "Paid",
    period: "February 2026",
  },
  {
    id: "inv-015",
    dormId: "dorm-001",
    tenantId: "tenant-003",
    tenantName: "Linh Tran",
    roomNumber: "102",
    amount: 850,
    dueDate: "2026-01-01",
    issuedDate: "2025-12-15",
    status: "Paid",
    period: "January 2026",
  },
  {
    id: "inv-005",
    dormId: "dorm-002",
    tenantId: "tenant-005",
    tenantName: "Amara Osei",
    roomNumber: "201",
    amount: 540,
    dueDate: "2026-03-01",
    issuedDate: "2026-02-15",
    status: "Overdue",
    period: "March 2026",
  },
  {
    id: "inv-006",
    dormId: "dorm-002",
    tenantId: "tenant-006",
    tenantName: "Daniel Novak",
    roomNumber: "201",
    amount: 540,
    dueDate: "2026-04-01",
    issuedDate: "2026-03-15",
    status: "Issued",
    period: "April 2026",
  },
  {
    id: "inv-007",
    dormId: "dorm-002",
    tenantId: "tenant-007",
    tenantName: "Priya Menon",
    roomNumber: "202",
    amount: 820,
    dueDate: "2026-04-01",
    issuedDate: "2026-03-15",
    status: "Paid",
    period: "April 2026",
  },
  {
    id: "inv-008",
    dormId: "dorm-002",
    tenantId: "tenant-008",
    tenantName: "Yuki Tanaka",
    roomNumber: "204",
    amount: 1200,
    dueDate: "2026-04-01",
    issuedDate: "2026-03-15",
    status: "Paid",
    period: "April 2026",
  },
  {
    id: "inv-009",
    dormId: "dorm-002",
    tenantId: "tenant-009",
    tenantName: "Nadia Flores",
    roomNumber: "204",
    amount: 1200,
    dueDate: "2026-04-01",
    issuedDate: "2026-03-15",
    status: "Issued",
    period: "April 2026",
  },
  {
    id: "inv-016",
    dormId: "dorm-002",
    tenantId: "tenant-005",
    tenantName: "Amara Osei",
    roomNumber: "201",
    amount: 540,
    dueDate: "2026-02-01",
    issuedDate: "2026-01-15",
    status: "Paid",
    period: "February 2026",
  },
  {
    id: "inv-010",
    dormId: "dorm-003",
    tenantId: "tenant-010",
    tenantName: "Ryo Hashimoto",
    roomNumber: "302",
    amount: 560,
    dueDate: "2026-03-15",
    issuedDate: "2026-03-01",
    status: "Overdue",
    period: "March 2026",
  },
  {
    id: "inv-011",
    dormId: "dorm-003",
    tenantId: "tenant-011",
    tenantName: "Kofi Asante",
    roomNumber: "302",
    amount: 560,
    dueDate: "2026-04-01",
    issuedDate: "2026-03-15",
    status: "Paid",
    period: "April 2026",
  },
  {
    id: "inv-012",
    dormId: "dorm-003",
    tenantId: "tenant-012",
    tenantName: "Isabelle Moreau",
    roomNumber: "304",
    amount: 1250,
    dueDate: "2026-04-01",
    issuedDate: "2026-03-15",
    status: "Draft",
    period: "April 2026",
  },
  {
    id: "inv-017",
    dormId: "dorm-003",
    tenantId: "tenant-012",
    tenantName: "Isabelle Moreau",
    roomNumber: "304",
    amount: 1250,
    dueDate: "2026-01-01",
    issuedDate: "2025-12-15",
    status: "Paid",
    period: "January 2026",
  },
];

export const DEMO_MAINTENANCE_TICKETS: WorkspaceMaintenanceTicket[] = [
  {
    id: "maint-001",
    dormId: "dorm-001",
    title: "Leaking faucet in bathroom",
    roomId: "room-001",
    roomNumber: "101",
    tenantName: "Sophea Kang",
    priority: "High",
    status: "In Progress",
    submittedDate: "2026-03-24",
    updatedDate: "2026-03-25",
    description: "The bathroom faucet has been dripping constantly for 3 days.",
    category: "Plumbing",
  },
  {
    id: "maint-002",
    dormId: "dorm-001",
    title: "AC unit not cooling",
    roomId: "room-003",
    roomNumber: "103",
    tenantName: "Ethan Park",
    priority: "High",
    status: "Open",
    submittedDate: "2026-03-25",
    updatedDate: "2026-03-25",
    description:
      "Air conditioning stopped working. Room temperature is unbearable.",
    category: "HVAC",
  },
  {
    id: "maint-003",
    dormId: "dorm-001",
    title: "Window latch feels loose",
    roomId: "room-002",
    roomNumber: "102",
    tenantName: "Linh Tran",
    priority: "Medium",
    status: "Open",
    submittedDate: "2026-03-23",
    updatedDate: "2026-03-23",
    description:
      "The window latch is not closing tightly and needs inspection.",
    category: "Structural",
  },
  {
    id: "maint-009",
    dormId: "dorm-001",
    title: "Bed frame inspection before move-in",
    roomId: "room-004",
    roomNumber: "104",
    tenantName: "Dorm Operations",
    priority: "Medium",
    status: "Open",
    submittedDate: "2026-03-27",
    updatedDate: "2026-03-27",
    description:
      "The maintenance team needs to tighten the bed frame and verify the mattress slats before the reserved move-in can proceed.",
    category: "Furniture",
    attachments: [
      {
        id: "maint-009-attachment-001",
        name: "inspection-checklist.txt",
        type: "text/plain",
        size: 18,
        dataUrl: "data:text/plain;base64,QmVkIGZyYW1lIGNoZWNrZWQu",
      },
    ],
  },
  {
    id: "maint-004",
    dormId: "dorm-002",
    title: "WiFi router replacement needed",
    roomId: "room-005",
    roomNumber: "201",
    tenantName: "Daniel Novak",
    priority: "Medium",
    status: "In Progress",
    submittedDate: "2026-03-22",
    updatedDate: "2026-03-24",
    description: "WiFi signal is very weak, router may need replacement.",
    category: "Electrical",
  },
  {
    id: "maint-005",
    dormId: "dorm-002",
    title: "Drain clog in bathroom",
    roomId: "room-006",
    roomNumber: "202",
    tenantName: "Priya Menon",
    priority: "High",
    status: "Open",
    submittedDate: "2026-03-26",
    updatedDate: "2026-03-26",
    description: "The bathroom drain is backing up after showers.",
    category: "Plumbing",
  },
  {
    id: "maint-006",
    dormId: "dorm-002",
    title: "Door lock stiff",
    roomId: "room-008",
    roomNumber: "204",
    tenantName: "Nadia Flores",
    priority: "Low",
    status: "Resolved",
    submittedDate: "2026-03-18",
    updatedDate: "2026-03-21",
    description: "Door lock requires excessive force to turn.",
    category: "Structural",
  },
  {
    id: "maint-007",
    dormId: "dorm-003",
    title: "Bathroom tiles cracked",
    roomId: "room-009",
    roomNumber: "301",
    tenantName: "N/A",
    priority: "Critical",
    status: "In Progress",
    submittedDate: "2026-03-20",
    updatedDate: "2026-03-23",
    description: "Multiple tiles cracked in main bathroom, safety hazard.",
    category: "Structural",
  },
  {
    id: "maint-008",
    dormId: "dorm-003",
    title: "Mold on ceiling corner",
    roomId: "room-010",
    roomNumber: "302",
    tenantName: "Ryo Hashimoto",
    priority: "Critical",
    status: "Open",
    submittedDate: "2026-03-26",
    updatedDate: "2026-03-26",
    description:
      "Visible mold growth in ceiling corner near window. Health concern.",
    category: "Structural",
  },
];

export const DEMO_ACTIVITY_FEED: WorkspaceActivityItem[] = (
  [
    {
      id: "act-001",
      dormId: "dorm-001",
      type: "payment",
      message: "Payment received for Room 103",
      actor: "Ethan Park",
      timestamp: "2026-03-26T05:42:00Z",
      meta: "$850.00",
    },
    {
      id: "act-002",
      dormId: "dorm-001",
      type: "maintenance",
      message: "New maintenance request — Room 102",
      actor: "Linh Tran",
      timestamp: "2026-03-26T04:15:00Z",
      meta: "Medium",
    },
    {
      id: "act-009",
      dormId: "dorm-001",
      type: "assignment",
      message: "Room 104 reserved for Jade Sullivan",
      actor: "Admin User",
      timestamp: "2026-03-27T09:20:00Z",
      meta: "Jade Sullivan",
    },
    {
      id: "act-010",
      dormId: "dorm-001",
      type: "maintenance",
      message: "New maintenance request — Room 104",
      actor: "Dorm Operations",
      timestamp: "2026-03-27T10:15:00Z",
      meta: "Furniture",
    },
    {
      id: "act-011",
      dormId: "dorm-001",
      type: "payment",
      message: "Payment received for Room 101",
      actor: "Sophea Kang",
      timestamp: "2026-03-03T08:40:00Z",
      meta: "$702.50",
    },
    {
      id: "act-012",
      dormId: "dorm-001",
      type: "payment",
      message: "Payment received for Room 101",
      actor: "Marcus Rivera",
      timestamp: "2026-02-03T07:55:00Z",
      meta: "$650.00",
    },
    {
      id: "act-013",
      dormId: "dorm-001",
      type: "payment",
      message: "Payment received for Room 102",
      actor: "Linh Tran",
      timestamp: "2026-01-03T09:10:00Z",
      meta: "$867.50",
    },
    {
      id: "act-003",
      dormId: "dorm-002",
      type: "payment",
      message: "Payment received for Room 202",
      actor: "Priya Menon",
      timestamp: "2026-03-25T18:30:00Z",
      meta: "$820.00",
    },
    {
      id: "act-004",
      dormId: "dorm-002",
      type: "assignment",
      message: "Suite 204 reached full occupancy",
      actor: "Admin",
      timestamp: "2026-03-25T14:00:00Z",
      meta: "2 residents",
    },
    {
      id: "act-005",
      dormId: "dorm-002",
      type: "maintenance",
      message: "Maintenance updated — Room 204",
      actor: "Maintenance Staff",
      timestamp: "2026-03-25T11:20:00Z",
      meta: "Resolved",
    },
    {
      id: "act-014",
      dormId: "dorm-002",
      type: "payment",
      message: "Payment received for Room 201",
      actor: "Amara Osei",
      timestamp: "2026-02-04T08:05:00Z",
      meta: "$540.00",
    },
    {
      id: "act-006",
      dormId: "dorm-003",
      type: "invoice",
      message: "Invoices drafted for April 2026",
      actor: "System",
      timestamp: "2026-03-25T08:00:00Z",
      meta: "3 invoices",
    },
    {
      id: "act-007",
      dormId: "dorm-003",
      type: "room",
      message: "Room 301 marked Under Maintenance",
      actor: "Admin",
      timestamp: "2026-03-23T10:00:00Z",
      meta: "Plumbing",
    },
    {
      id: "act-008",
      dormId: "dorm-003",
      type: "maintenance",
      message: "Critical mold ticket opened for Room 302",
      actor: "Ryo Hashimoto",
      timestamp: "2026-03-26T01:30:00Z",
      meta: "Critical",
    },
    {
      id: "act-015",
      dormId: "dorm-003",
      type: "payment",
      message: "Payment received for Room 304",
      actor: "Isabelle Moreau",
      timestamp: "2026-01-04T07:30:00Z",
      meta: "$1,267.50",
    },
  ] satisfies WorkspaceActivityItem[]
).sort(
  (left, right) =>
    new Date(right.timestamp).getTime() - new Date(left.timestamp).getTime(),
);

export const DEMO_CHEFS: WorkspaceChef[] = [
  {
    id: "chef-001",
    dormId: "dorm-001",
    name: "Chef Kim",
    email: "chef.kim@sunrisedorm.app",
    shift: "Morning",
    specialty: "Dorm Meal Planning",
    status: "Active",
  },
  {
    id: "chef-002",
    dormId: "dorm-002",
    name: "Chef Dara",
    email: "chef.dara@riversideresidences.app",
    shift: "Split",
    specialty: "Bulk Dinner Service",
    status: "Active",
  },
  {
    id: "chef-003",
    dormId: "dorm-003",
    name: "Chef Sokha",
    email: "chef.sokha@northgatehouse.app",
    shift: "Evening",
    specialty: "Late Service & Inventory",
    status: "Invited",
    invitationLifecycleState: "pending",
  },
];

export const DEMO_TENANT_MEAL_PREFERENCES: TenantMealPreference[] = [
  {
    tenantId: "tenant-001",
    plan: "Full Board",
    notes: "Vegetarian meals on weekdays.",
  },
  {
    tenantId: "tenant-003",
    plan: "Breakfast Only",
    notes: "Prefers early service before class.",
  },
  {
    tenantId: "tenant-004",
    plan: "Half Board",
    notes: "Lunch and dinner preferred after athletics training.",
  },
  {
    tenantId: "tenant-007",
    plan: "Half Board",
    notes: "Lunch and dinner preferred on weekdays.",
  },
  {
    tenantId: "tenant-009",
    plan: "Full Board",
    notes: "Avoid shellfish ingredients.",
  },
  {
    tenantId: "tenant-012",
    plan: "Breakfast Only",
    notes: "Light breakfast is preferred before lectures.",
  },
];

export const DEMO_MEALS: MealItemRecord[] = buildDemoMeals();

export const DEFAULT_MEAL_PLAN: MealPlan = "No Meal Plan";
